#!/usr/bin/env python
"""This git extension findest the ``latest'' among commits.

Run git-latest --help to see help for usage

Copyright(C) Stanford University 2010
Author ykk
Date February 2010
"""
import commands
import getopt
import sys

def usage():
    """Display usage
    """
    print "Usage "+sys.argv[0]+" <options> commit(s)\n"+\
          "Options:\n"+\
          "-h/--help\n\tPrint this usage guide\n"+\
          ""

def later(commit1, commit2):
    """ Get later commit
    """
    cmd = commands.getoutput("git log --pretty=oneline "+commit1+\
                             ".."+commit2)
    if (cmd.strip() == ""):
        return commit1
    else:
        return commit2

#Parse options and arguments
##until commit
since=None
try:
    opts, args = getopt.getopt(sys.argv[1:], "h",
                               ["help"])
except getopt.GetoptError:
    usage()
    sys.exit(2)

for opt,arg in opts:
    if (opt in ("-h","--help")):
        usage()
        sys.exit(0)
    else:
        print "Unhandled option :"+opt
        usage()
        sys.exit(2)

#Check there is at least 1 commit
if not (len(args) > 0):
    print "At least one commit needed as argument"
    usage()
    sys.exit(2)

latest = args[0]
for i in range(1,len(args)):
    latest=later(latest, args[i])
print latest
